### PR TITLE
Added the feature progressbar

### PR DESCRIPTION
**Pull request by roykrikke**
Added the feature progressbar, see ivandokov#21

I used https://github.com/tqdm/tqdm for the progressbar

In addition the readme.md modified with documentation for the progressbar. Also small mistakes in the readme.md have been fixed.

### CODE REVIEW

**Comment by ivandokov** [comment]
I just tested the code and it's looking great! There is only one thing that bothers me - the name of the option.
Even though we are actually showing a progress bar we are also showing additional data alongside it and I think `--progressbar` is not the best option. I'm thinking for something shorter and more general such as `--progress`.
Thoughts?

**Comment by ivandokov** [comment]
I forgot to mention that it will be quite nice if we can combine the regular output with the progress bar but that's a topic for a separate PR as I'm fine merging this one as soon as the option name is changed.

**Comment by roykrikke** [comment]
I was thinking about what you wrote. The name of the option was just one I picked. We could change it to `--progress`

But your other comment got me thinking and I played a bit with some options e.g:
```
roy@computron:~/phockup_try$ ./phockup.py --dry-run  --progressbar tests/input/ tests/
[2021-08-24 21:17:26] - [WARNING] - Dry-run phockup (does a trial run with no permanent changes)...
tests/input/!#$%'+-.^_`~.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/UNKNOWN.jpg => tests/2017/10/06/20171006-231439.jpg
tests/input/date_20170101_010101.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/exif.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/exif.mp4 => tests/2017/01/01/20170101-010101.mp4
tests/input/link_to_date_20170101_010101.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/other.txt => tests/unknown/other.txt
tests/input/phockup's exif test.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/xmp.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/xmp_ext.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/xmp_noext.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/sub_folder/date_20180101_010101.jpg => tests/2018/01/01/20180101-010101.jpg
tests/input/sub_sub_folder/date_20180101_010101.jpg => tests/2018/01/01/20180101-010101.jpg
Progressing: 'tests/input' : 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:03<00:00,  4.81file/s]
```
Where you see a nice bar which is updated with every step, plus you can still see the normal output of phockup.

**There is only one topic which I can't fix yet and which may not need to be fixed if we think it's okay. I will explain. Read and look carefully please, because you will only see it if you look closely.**

If I run `tqdm `with  `leave=False` and press of `Ctrl-C` in a run all is fine and the program stops perfect. But add the end of a normal run (so without a press of `Ctrl-C`) the bar will **not** be visible for the user. Below the two outputs:
```
roy@computron:~/phockup_try$ ./phockup.py --dry-run  --progressbar tests/input/ tests/
[2021-08-24 21:26:34] - [WARNING] - Dry-run phockup (does a trial run with no permanent changes)...
tests/input/!#$%'+-.^_`~.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/UNKNOWN.jpg => tests/2017/10/06/20171006-231439.jpg
tests/input/date_20170101_010101.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/exif.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/exif.mp4 => tests/2017/01/01/20170101-010101.mp4
tests/input/link_to_date_20170101_010101.jpg => tests/2017/01/01/20170101-010101.jpg
Progressing: 'tests/input' :  41%|███████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                             | 7/17 [00:00<00:01,  8.77file/s]^C[2021-08-24 21:26:35] - [ERROR] - Exiting phockup...
```
```
roy@computron:~/phockup_try$ ./phockup.py --dry-run  --progressbar tests/input/ tests/
[2021-08-24 21:29:16] - [WARNING] - Dry-run phockup (does a trial run with no permanent changes)...
tests/input/!#$%'+-.^_`~.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/UNKNOWN.jpg => tests/2017/10/06/20171006-231439.jpg
tests/input/date_20170101_010101.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/exif.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/exif.mp4 => tests/2017/01/01/20170101-010101.mp4
tests/input/link_to_date_20170101_010101.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/other.txt => tests/unknown/other.txt
tests/input/phockup's exif test.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/xmp.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/xmp_ext.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/xmp_noext.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/sub_folder/date_20180101_010101.jpg => tests/2018/01/01/20180101-010101.jpg
tests/input/sub_sub_folder/date_20180101_010101.jpg => tests/2018/01/01/20180101-010101.jpg
roy@computron:~/phockup_try$
```
But if I run `tqdm `with  `leave=True` and press of `Ctrl-C`  it prints and extra bar. But add the end of a normal run (so without a press of `Ctrl-C`) the bar will be visible for the user. Below the two outputs:
```
roy@computron:~/phockup_try$ ./phockup.py --dry-run  --progressbar tests/input/ tests/
[2021-08-24 21:31:18] - [WARNING] - Dry-run phockup (does a trial run with no permanent changes)...
tests/input/!#$%'+-.^_`~.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/UNKNOWN.jpg => tests/2017/10/06/20171006-231439.jpg
tests/input/date_20170101_010101.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/exif.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/exif.mp4 => tests/2017/01/01/20170101-010101.mp4
tests/input/link_to_date_20170101_010101.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/other.txt => tests/unknown/other.txt
tests/input/phockup's exif test.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/xmp.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/xmp_ext.jpg => tests/2017/01/01/20170101-010101.jpg
Progressing: 'tests/input' :  71%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                              | 12/17 [00:01<00:00, 11.38file/s]
[2021-08-24 21:31:20] - [ERROR] - Exiting phockup...
Progressing: 'tests/input' :  82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                     | 14/17 [00:01<00:00, 11.43file/s]
roy@computron:~/phockup_try$

```
```
roy@computron:~/phockup_try$ ./phockup.py --dry-run  --progressbar tests/input/ tests/
[2021-08-24 21:31:41] - [WARNING] - Dry-run phockup (does a trial run with no permanent changes)...
tests/input/!#$%'+-.^_`~.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/UNKNOWN.jpg => tests/2017/10/06/20171006-231439.jpg
tests/input/date_20170101_010101.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/exif.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/exif.mp4 => tests/2017/01/01/20170101-010101.mp4
tests/input/link_to_date_20170101_010101.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/other.txt => tests/unknown/other.txt
tests/input/phockup's exif test.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/xmp.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/xmp_ext.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/xmp_noext.jpg => tests/2017/01/01/20170101-010101.jpg
tests/input/sub_folder/date_20180101_010101.jpg => tests/2018/01/01/20180101-010101.jpg
tests/input/sub_sub_folder/date_20180101_010101.jpg => tests/2018/01/01/20180101-010101.jpg
Progressing: 'tests/input' : 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:03<00:00,  4.79file/s]
roy@computron:~/phockup_try$
```

Personally, I don't think it's a big deal if the bar disappears after the program has done its job and just shows the normal output. That's why I suggest we go for the `leave=False` option. But before I continue working on it further. I'll wait for your feedback first.  I'm curious about your opinion and what you think about it.

**Comment by ivandokov** [comment]
To be honest I couldn't really understand the explanation and so I teted it locally and I think the `leave=False` works better in regards of canceling the process before it ends on itself, but I do not see the regulard output. I guess you haven't committed this part of the code which is fine as you are still working on it.

**Comment by roykrikke** [comment]
I was already afraid of that. I have made the changes according to the feedback. Just look at it.

The printing of functions `process_file `and `process_xmp` needs some refactoring if we really want to implement it really neatly in  `walk_directory`. For now I wanted to commit it like this, and think in the background how to do the refactoring.

**Comment by roykrikke** [comment]
ivandokov do you have an idea when it will merged?

**Comment by ivandokov** [comment]
I'm sorry for being absent I am rushed by deadlines over here and couldn't take a look.
I have only one comment - can you please replace progressbar with progress across the PR and I'll merge it. 
Thank you!

**Comment by roykrikke** [comment]
No problem, we all have that sometimes. Anyway, request has been processed.

**Comment by roykrikke** [comment]
Whooo, that was merged in 5 seconds. It must be some kind of record ;-)

**Comment by ivandokov** [comment]
5 seconds after a few days delay :)

**Pull request merged**
