### PR TITLE
Further test/lint improvements

### PR DESCRIPTION
**Pull request by inverse**
- Add mypy for static analysis of types
  - Needs type annotations to be properly leveraged, but that can be done after
- Add `pytest-socket` to ensure no network IO on tests
- `test_progress()` was declared twice, I assumed only the last one was being executed and the first was always failing so removed the first as I didnt see what it was actually trying to test. 
- Un-ignore `F811` from flake8

### CODE REVIEW

**Comment by roykrikke** [comment]
Hello @inverse, great commit. I reviewed all an ticked the view checkboxs. There is one exception btw. (and yes I introduced that myself 😆) Please change to the code below.

```
def test_progress():
    shutil.rmtree('output', ignore_errors=True)
    Phockup('input', 'output', progress=True)
    dir1 = 'output/2017/01/01'
    dir2 = 'output/2017/10/06'
    dir3 = 'output/unknown'
    dir4 = 'output/2018/01/01/'
    assert os.path.isdir(dir1)
    assert os.path.isdir(dir2)
    assert os.path.isdir(dir3)
    assert os.path.isdir(dir4)
    assert len([name for name in os.listdir(dir1) if
                os.path.isfile(os.path.join(dir1, name))]) == 3
    assert len([name for name in os.listdir(dir2) if
                os.path.isfile(os.path.join(dir2, name))]) == 1
    assert len([name for name in os.listdir(dir3) if
                os.path.isfile(os.path.join(dir3, name))]) == 1
    assert len([name for name in os.listdir(dir4) if
                os.path.isfile(os.path.join(dir4, name))]) == 1
    shutil.rmtree('output', ignore_errors=True)
```


@inverse and @ivandokov 
I checked the the test coverage with `pytest --cov-report term-missing:skip-covered --cov=src tests/`
```
----------- coverage: platform linux, python 3.9.2-final-0 -----------
Name             Stmts   Miss  Cover   Missing
----------------------------------------------
src/date.py         75      3    96%   112, 115-116
src/exif.py         17      1    94%   14
src/phockup.py     189      7    96%   82, 106, 202-205, 222, 234
----------------------------------------------
TOTAL              287     11    96%
```
Then I saw that we are not testing lines 202-205 of src/phockup.py  and in my opinion we should. When trying to realists it, I found behavior that I can't quite explain and need your input.

When i run `./phockup.py --dry-run --debug tests/input/ tests/output/` the file  `tests/input/other.txt `is moved to `tests/output/unknown/other.txt`
`[2021-09-10 08:29:51] - [INFO] - tests/input/other.txt => tests/output/unknown/other.txt`

But when I run `./phockup.py --dry-run --debug --file-type=image tests/input/ tests/output/` the file is skipped.
`[2021-09-10 08:31:34] - [INFO] - tests/input/other.txt => skipped, file is 'None' but looking for 'image'`

I don't know if this is default behavior and that's why the option of `--file-type` exists. If so, the documentation needs to be modified. If the default behavior should be such that unknown files files should not be sent to unknown folder, then we have to change something in the code. What is the behavior we expect?

**Comment by ivandokov** [comment]
Drh run should not move files regardless of other flags.

**Comment by roykrikke** [comment]
Hello @ivandokov,

I think you missed my point. Anyway, I just did an extra check without `--dry-run`

```
roy@computron:~/phockup$ ./phockup.py --debug tests/input/ tests/output/
[2021-09-10 16:03:04] - [WARNING] - Output directory 'tests/output' does not exist, creating now
[2021-09-10 16:03:04] - [INFO] - tests/input/!#$%'+-.^_`~.jpg => tests/output/2017/01/01/20170101-010101.jpg
[2021-09-10 16:03:05] - [INFO] - tests/input/UNKNOWN.jpg => tests/output/2017/10/06/20171006-231439.jpg
[2021-09-10 16:03:05] - [INFO] - tests/input/date_20170101_010101.jpg => tests/output/2017/01/01/20170101-010101-2.jpg
[2021-09-10 16:03:05] - [INFO] - tests/input/exif.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101.jpg
[2021-09-10 16:03:05] - [INFO] - tests/input/exif.mp4 => tests/output/2017/01/01/20170101-010101.mp4
[2021-09-10 16:03:05] - [INFO] - tests/input/link_to_date_20170101_010101.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-                                                        010101-2.jpg
[2021-09-10 16:03:05] - [INFO] - tests/input/other.txt => tests/output/unknown/other.txt
[2021-09-10 16:03:05] - [INFO] - tests/input/phockup's exif test.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101.jp                                                        g
[2021-09-10 16:03:06] - [INFO] - tests/input/xmp.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101.jpg
[2021-09-10 16:03:06] - [INFO] - tests/input/xmp_ext.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101.jpg
[2021-09-10 16:03:06] - [INFO] - tests/input/xmp_noext.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101.jpg
[2021-09-10 16:03:06] - [INFO] - tests/input/sub_folder/date_20180101_010101.jpg => tests/output/2018/01/01/20180101-010101.jpg
roy@computron:~/phockup$ rm -rf tests/output/
roy@computron:~/phockup$ ls -all tests/output/
ls: cannot access 'tests/output/': No such file or directory
roy@computron:~/phockup$ ./phockup.py --debug --file-type=image tests/input/ tests/output/
[2021-09-10 16:03:43] - [WARNING] - Output directory 'tests/output' does not exist, creating now
[2021-09-10 16:03:43] - [INFO] - tests/input/!#$%'+-.^_`~.jpg => tests/output/2017/01/01/20170101-010101.jpg
[2021-09-10 16:03:43] - [INFO] - tests/input/UNKNOWN.jpg => tests/output/2017/10/06/20171006-231439.jpg
[2021-09-10 16:03:43] - [INFO] - tests/input/date_20170101_010101.jpg => tests/output/2017/01/01/20170101-010101-2.jpg
[2021-09-10 16:03:43] - [INFO] - tests/input/exif.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101.jpg
[2021-09-10 16:03:43] - [INFO] - tests/input/exif.mp4 => skipped, file is 'video' but looking for 'image'
[2021-09-10 16:03:43] - [INFO] - tests/input/link_to_date_20170101_010101.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101-2.jpg
[2021-09-10 16:03:44] - [INFO] - tests/input/other.txt => skipped, file is 'None' but looking for 'image'
[2021-09-10 16:03:44] - [INFO] - tests/input/phockup's exif test.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101.jpg
[2021-09-10 16:03:44] - [INFO] - tests/input/xmp.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101.jpg
[2021-09-10 16:03:44] - [INFO] - tests/input/xmp_ext.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101.jpg
[2021-09-10 16:03:44] - [INFO] - tests/input/xmp_noext.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101.jpg
[2021-09-10 16:03:44] - [INFO] - tests/input/sub_folder/date_20180101_010101.jpg => tests/output/2018/01/01/20180101-010101.jpg
roy@computron:~/phockup$
```

The behavior as I wrote up here is the same with or without the `--dry-run` option. I wonder if this is correct behavior. 
Below is a brief summary. Hopefully that makes my point clearer.
```
./phockup.py --debug tests/input/ tests/output/
[2021-09-10 16:03:05] - [INFO] - tests/input/other.txt => tests/output/unknown/other.txt
```

```
./phockup.py --debug --file-type=image tests/input/ tests/output/
[2021-09-10 16:03:44] - [INFO] - tests/input/other.txt => skipped, file is 'None' but looking for 'image'
```

**Comment by inverse** [comment]
@roykrikke updated test as requested 👍🏼

**Comment by roykrikke** [comment]
> 
> 
> Hello @ivandokov,
> 
> I think you missed my point. Anyway, I just did an extra check without `--dry-run`
> 
> ```
> roy@computron:~/phockup$ ./phockup.py --debug tests/input/ tests/output/
> [2021-09-10 16:03:04] - [WARNING] - Output directory 'tests/output' does not exist, creating now
> [2021-09-10 16:03:04] - [INFO] - tests/input/!#$%'+-.^_`~.jpg => tests/output/2017/01/01/20170101-010101.jpg
> [2021-09-10 16:03:05] - [INFO] - tests/input/UNKNOWN.jpg => tests/output/2017/10/06/20171006-231439.jpg
> [2021-09-10 16:03:05] - [INFO] - tests/input/date_20170101_010101.jpg => tests/output/2017/01/01/20170101-010101-2.jpg
> [2021-09-10 16:03:05] - [INFO] - tests/input/exif.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101.jpg
> [2021-09-10 16:03:05] - [INFO] - tests/input/exif.mp4 => tests/output/2017/01/01/20170101-010101.mp4
> [2021-09-10 16:03:05] - [INFO] - tests/input/link_to_date_20170101_010101.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-                                                        010101-2.jpg
> [2021-09-10 16:03:05] - [INFO] - tests/input/other.txt => tests/output/unknown/other.txt
> [2021-09-10 16:03:05] - [INFO] - tests/input/phockup's exif test.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101.jp                                                        g
> [2021-09-10 16:03:06] - [INFO] - tests/input/xmp.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101.jpg
> [2021-09-10 16:03:06] - [INFO] - tests/input/xmp_ext.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101.jpg
> [2021-09-10 16:03:06] - [INFO] - tests/input/xmp_noext.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101.jpg
> [2021-09-10 16:03:06] - [INFO] - tests/input/sub_folder/date_20180101_010101.jpg => tests/output/2018/01/01/20180101-010101.jpg
> roy@computron:~/phockup$ rm -rf tests/output/
> roy@computron:~/phockup$ ls -all tests/output/
> ls: cannot access 'tests/output/': No such file or directory
> roy@computron:~/phockup$ ./phockup.py --debug --file-type=image tests/input/ tests/output/
> [2021-09-10 16:03:43] - [WARNING] - Output directory 'tests/output' does not exist, creating now
> [2021-09-10 16:03:43] - [INFO] - tests/input/!#$%'+-.^_`~.jpg => tests/output/2017/01/01/20170101-010101.jpg
> [2021-09-10 16:03:43] - [INFO] - tests/input/UNKNOWN.jpg => tests/output/2017/10/06/20171006-231439.jpg
> [2021-09-10 16:03:43] - [INFO] - tests/input/date_20170101_010101.jpg => tests/output/2017/01/01/20170101-010101-2.jpg
> [2021-09-10 16:03:43] - [INFO] - tests/input/exif.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101.jpg
> [2021-09-10 16:03:43] - [INFO] - tests/input/exif.mp4 => skipped, file is 'video' but looking for 'image'
> [2021-09-10 16:03:43] - [INFO] - tests/input/link_to_date_20170101_010101.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101-2.jpg
> [2021-09-10 16:03:44] - [INFO] - tests/input/other.txt => skipped, file is 'None' but looking for 'image'
> [2021-09-10 16:03:44] - [INFO] - tests/input/phockup's exif test.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101.jpg
> [2021-09-10 16:03:44] - [INFO] - tests/input/xmp.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101.jpg
> [2021-09-10 16:03:44] - [INFO] - tests/input/xmp_ext.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101.jpg
> [2021-09-10 16:03:44] - [INFO] - tests/input/xmp_noext.jpg => skipped, duplicated file tests/output/2017/01/01/20170101-010101.jpg
> [2021-09-10 16:03:44] - [INFO] - tests/input/sub_folder/date_20180101_010101.jpg => tests/output/2018/01/01/20180101-010101.jpg
> roy@computron:~/phockup$
> ```
> 
> The behavior as I wrote up here is the same with or without the `--dry-run` option. I wonder if this is correct behavior.
> Below is a brief summary. Hopefully that makes my point clearer.
> 
> ```
> ./phockup.py --debug tests/input/ tests/output/
> [2021-09-10 16:03:05] - [INFO] - tests/input/other.txt => tests/output/unknown/other.txt
> ```
> 
> ```
> ./phockup.py --debug --file-type=image tests/input/ tests/output/
> [2021-09-10 16:03:44] - [INFO] - tests/input/other.txt => skipped, file is 'None' but looking for 'image'
> ```

Hello @ivandokov did you see my message?

**Comment by ivandokov** [comment]
@roykrikke I got your point now and it is indeed a tricky question. But to be honest I think it is working as expected because when you are not specifying the type of file you should expect every file to be copied/moved to the output directory but when you are looking for a specific type of files everything else should be skipped. Did I answer your question?

**Comment by roykrikke** [comment]
@ivandokov Yes this answers my question. In a next update of phockup from my-side I will see if I can manage to pass photos and videos at the same time as cmd option. In addition, I will also try to clarify the description in the help description.

**Pull request merged**
