### PR TITLE
idea... lets add docker ?

### PR DESCRIPTION
**Pull request by sebastianovide**
what do you think ?

### CODE REVIEW

**Comment by ivandokov** [comment]
I'm not against it but I need to see a real benefit compared to the snap package. Why would anyone want to install Docker in order to sort his / hers images. I get it for developers with already installed Docker or maybe for Windows users but it looks even more advanced for them.

**Comment by sebastianovide** [comment]
for example to use it in Windows or Mac :) I'm using it in Mac in which I already have docker. After that it is just 1 command line to run phockup from docker without installing anything else...

**Comment by ivandokov** [comment]
Brew is quite popular package manager for macOS and our dependencies are just a few.

**Comment by sebastianovide** [comment]
yes, you are right. It is: Even if in some companies, the IS department don't provide admin access and the software need to be pre approved. (Docker is a common pre approved software and brew is not )
well, just one idea to give it more flexibility.

**Comment by ivandokov** [comment]
That's a valid but kind of edge case. Even if we add the Docker container how can we pass the various params to the container? And the requirement for a specific input directory is not really good. Is there a way to pass the input and output directories as params. 
Sorry for my questions - Docker is still in my TODO list :)

**Comment by sebastianovide** [comment]
the short answer us yes, you can :). All is configurable !.... even if I'd rather offer the simplest solution, that that needs the lest number of command lines to use,  and then make it configurable...(if necessary)  but, as in docker you can import another docker file, you are inheriting flexibility.

just to give you an example, A couple of days ago I needed to help a colleague to debug a PostGIS query. In order to do that, I should install PostgreGIS + pgadmin4 + gdal. Surely you can do it with brew..... and wait.... and wait.... and eventually use it.... and then clean up the machine... Very time consuming. Or... a **single command line** that creates it all... in a matter of minutes !. So, in the mean time that I was waiting for brew to install the first dependency, I created a docker-compose file, and run it... when I've finished, I've simply didn't do nothing. Containers are still here, in my machine. They don't bother me as they don't touch my system... neat !

**Comment by ivandokov** [comment]
You don't have to convince me that Docker is good, but I do not see how we can easily implement it in our case. Maybe we can introduce another binary that is proxying commands to the docker container but I think this is a whole mini-project on its own. If you think you are able to handle such implementation I agree to have it alongside the regular way of using the code. 

Something like this:
`phockup-docker inputdir outputdir --other-options`

**Comment by sebastianovide** [comment]
what about these options, 

1.  use docker-compose. Need to create the 2 folders (original,sorted) and the command line to run is `docker-compose up`

1. mount the whole FS in /mnt. Then you can pass as many parameters so you like to your script
```
docker image build -t phockup .
docker run -v /:/mnt -it phockup phockup /mnt/originals /mnt/sorted -d YYYY/YYYY-MM/YYYY-MM-DD -m
```

1. same as before but you publish your container. So there is not need to run the build (single command line)

**Comment by rwenz3l** [comment]
using compose is way overkill for this tool. A common approach is to provide a simple dockerfile/container and then do:

```
docker run -it [docker-options] phockup/phockup:latest phockup.py [phockup-options]
```

that is indeed helpful if you cannot or do not want to mess with your environment.

**Comment by Avamander** [comment]
I think this is a good idea and would avoid a lot of the pain `snap` causes to people.

**Comment by timmillwood** [comment]
I do exactly what @rwenz3l is saying. I wanted to run this on my Synology NAS for sorting old photos into a new folder structure.

Here's my Dockerfile
```
FROM python:latest

RUN apt-get update -y
RUN apt-get install apt-utils -y
RUN apt-get install libimage-exiftool-perl -y
RUN curl -L https://github.com/ivandokov/phockup/archive/latest.tar.gz -o phockup.tar.gz
RUN tar -zxf phockup.tar.gz
RUN mv phockup-* /opt/phockup
RUN ln -s /opt/phockup/phockup.py /usr/local/bin/phockup
```

I then ran it with `docker run -v /:/ds920 phockup:Dockerfile phockup /ds920/volume1/oldnas/Photo\ library /ds920/volume1/homes/tim/Drive/Moments/Camera`

**Comment by ivandokov** [comment]
Thanks to everyone involved with this PR I have added a Dockerfile to the repo and built a container. 
I chose to use @rwenz3l's suggestion and allow passing all arguments to the container instead of predefining the input and output directories as it is in this PR.
I added some info to [the readme](https://github.com/ivandokov/phockup#docker) how to use Docker to process media files.
Any improvements to the way I setup the Dockerfile or the way I explained how to use it are welcome. My Docker experience is limited.

**Comment by ivandokov** [comment]
I just pushed a new version of the docker image which is 10x smaller (~95MB) than the previous one) as it is based on `python:3.8.7-alpine` which is on itself based on Alpine linux image.

**Pull request closed without merging**
