### PR TITLE
RPM support

### PR DESCRIPTION
**Pull request by suhancz**
This commit adds RPM package support to phockup

### CODE REVIEW

**Comment by ivandokov** [comment]
@suhancz thank you for this PR. Can you please let me know what else should I do to make phockup available for RPM based distros? I have no experience with this at all. 

PRs for `apt` support are also appreciated.

PS: I am not sure how these distro repositories are going to pick up new versions of the software. If they use Github directly it will be the best but if they require manual deploy of new versions a PR for Github Action will be greatly appreciated.

**Comment by suhancz** [comment]
@ivandokov I took the liberty to create my own [COPR for Fedora 31-33 and rawhide](https://copr.fedorainfracloud.org/coprs/suhanc/phockup/) to make sure my own systems take up the package, but that one points to [my fork](https://github.com/suhancz/phockup). To make sure this gets rebuilt with all *your* new versions I'd suggest to [create your own](https://docs.pagure.org/copr.copr/screenshots_tutorial.html#screenshots-tutorial) and make it [point to your Github repo](https://docs.pagure.org/copr.copr/user_documentation.html#scm) and also create a [webhook](https://docs.pagure.org/copr.copr/user_documentation.html#github-webhooks) so all your pushes get compiled in COPR.

For now to keep the RPM maintained is that you should keep an eye on the following:
 * `phockup.spec`
   * [version and release](https://github.com/suhancz/phockup/blob/master/phockup.spec#L7-L8)
   * [install paths](https://github.com/suhancz/phockup/blob/master/phockup.spec#L29-L38) (`%{buildroot}` is a pointer to the target root directory of the OS you're installing to)
   * [installed files](https://github.com/suhancz/phockup/blob/master/phockup.spec#L40-L43) (they specify what to actually install from `%{buildroot}`)
   * [changelog](https://github.com/suhancz/phockup/blob/master/phockup.spec#L45-L47)
 * [phockup-rpm.sh](https://github.com/suhancz/phockup/blob/master/phockup-rpm.sh) (I'm not *totally* sure this is needed at all, just as I've seen [snap-specific paths in your phockup.sh](https://github.com/ivandokov/phockup/blob/master/phockup.sh#L7-L9) I considered safer to have one for systems without having snap installed - sadly my main OS, Fedora Silverblue doesn't support snap, that's why I decided to write and submit this patch)

For `apt` support I'm aware of the existence of [Launchpad](https://help.launchpad.net/) which should be similar to COPR, though I don't have much experience on Debian packaging neither, so hopefully some fellow user of Phockup who'd enjoy integrating it to their preferred distro would pick it up :)

**Comment by ivandokov** [comment]
To be honest this is way out of my expertise and I am not sure how to handle this PR. 
I am going to move all releases deployment to a Github Automation(s) soon and I do not want to be bothered by manual deployments to any of the distro repos. 
If you can automate the process with a Github Action it will be much appreciated. 
Basically it should **Just Works™️** or I will not be able to use it.

**Comment by ivandokov** [comment]
I'm closing this as we need automated solution for updating the RPM repo and I am not able to do it so PR with that included is welcome!

**Comment by suhancz** [comment]
Sorry for the late response, I just got some time to look into [Github Actions](https://github.com/marketplace/actions/rpm-build) and seems you can't avoid a `.spec` file. I'll try it on my own repo though to see if it works and satisfies your needs, stay tuned.

**Pull request closed without merging**
