### PR TITLE
Fix to preserve uppercase when using the --original-names option

### PR DESCRIPTION
**Pull request by pauloup**
So a filename like "IMG_2018..." no longer becomes "img_2018..."

### CODE REVIEW

**Comment by ivandokov** [comment]
@pauloup I added unit test to the PR. Please let me know once you take a look and if you have any questions before I merge the code.

**Comment by pauloup** [comment]
@ivandokov Perfect! I looked at it and I think I understood the code and how a unit tests works.

**Comment by pauloup** [comment]
I think I found a problem: In `test_process_image_unknown`, should not the filename still change from `UNKNOWN.jpg` to `unknown.jpg` since the "--original-names" option _is missing_ in this particular unit test?

So I think lines 177 and 178 should be:
```
Phockup('input', 'output').process_file("input/UNKNOWN.jpg")
assert os.path.isfile("output/unknown/unknown.jpg")
```

**Comment by pauloup** [comment]
So why does it raises an AssertionError when I do the unit test?
```
=============================================================================== FAILURES ================================================================================
______________________________________________________________________ test_process_image_unknown _______________________________________________________________________

mocker = <pytest_mock.MockFixture object at 0x7fe3b0a3c668>

    def test_process_image_unknown(mocker):
        shutil.rmtree('output', ignore_errors=True)
        mocker.patch.object(Phockup, 'check_directories')
        mocker.patch.object(Phockup, 'walk_directory')
        exif = {"input/UNKNOWN.jpg": {
            "MIMEType": "image/jpeg"
        }}
        Phockup('input', 'output').process_file(exif, "input/UNKNOWN.jpg")
>       assert os.path.isfile("output/unknown/UNKNOWN.jpg")
E       AssertionError: assert False
E        +  where False = <function isfile at 0x7fe3b4a059d8>('output/unknown/UNKNOWN.jpg')
E        +    where <function isfile at 0x7fe3b4a059d8> = <module 'posixpath' from '/usr/lib/python3.6/posixpath.py'>.isfile
E        +      where <module 'posixpath' from '/usr/lib/python3.6/posixpath.py'> = os.path

test_phockup.py:176: AssertionError
------------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------------
input/UNKNOWN.jpg => output/unknown/unknown.jpg
================================================================== 1 failed, 32 passed in 2.04 seconds ==================================================================
```

**Comment by pauloup** [comment]
Maybe it's a issue of Windows and Linux, as pointed by this commnet https://stackoverflow.com/questions/17277566/check-os-path-isfilefilename-with-case-sensitive-in-python#comment25048026_17277566

**Pull request merged**
