### PR TITLE
Enable basic pre-commit

### PR DESCRIPTION
**Pull request by inverse**
Leverage the [pre-commit](https://pre-commit.com/) framework to perform some basic code quality tasks - can be extended in the future.

Configured to run on CI too.

### CODE REVIEW

**Comment by ivandokov** [comment]
@roykrikke can you give your opinion about this as you already did some automated code linting in another PR and you have some experience with this I guess.

**Comment by roykrikke** [comment]
@ivandokov I was reviewing Feature/threaded #123  I will check it when ready with the other review.

**Comment by roykrikke** [comment]
@ivandokov and @inverse I was unaware of https://pre-commit.com/ tool. I've read the documentation and think we can safely integrate this. It would be good to include a section in the readme like "Development > Running tests"  but then of course a new session describing this feature.

**Comment by inverse** [comment]
@roykrikke @ivandokov updated!

**Comment by inverse** [comment]
@roykrikke I consolidated the lint on CI to use flake8 in pre-commit .

I had to disable `F811` as it caused an issue with the `test_progress()` as it's declared twice and renaming caused the tests to fail.

**Comment by ivandokov** [comment]
Hey @inverse, thank you for this PR.
I tried to commit to the changelog and tag a new version but I get the following:

```
No .pre-commit-config.yaml file was found
- To temporarily silence this, run `PRE_COMMIT_ALLOW_NO_CONFIG=1 git ...`
- To permanently silence this, install pre-commit with the --allow-missing-config option
- To uninstall pre-commit run `pre-commit uninstall`
```

Are we missing a config file?

**Comment by inverse** [comment]
@ivandokov I got an email that it wasn't working but cant see it here, are you unblocked?

**Comment by ivandokov** [comment]
I figured it out.... forgot to pull the master after I merged it 🤦‍♂️

**Pull request merged**
