### PR TITLE
Implementation of --maxdepth to limit recursion of input directory

### PR DESCRIPTION
**Pull request by unapproachable**
Implementation of --maxdepth from https://github.com/ivandokov/phockup/issues/92.  

No tests were written because it's actually beyond my capabilities to write the test.  Maybe someone can help.

Merge collisions exist from the prior commit, possibly related to the Windows platform, but I'm unclear how to resolve them.

### CODE REVIEW

**Comment by ivandokov** [comment]
You have to pull master and go to your branch `feature/maxdepth` and do `git merge master` to merge the latest changes to your feature branch. Then you will have to resolve te conflicts locally and when you do you can push the update on your branch and then we will see a cleaner diff in this PR.

**Comment by unapproachable** [comment]
Thanks for the suggestion.  I am pretty sure I did this:

```shell
P:\Projects\phockup>git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

P:\Projects\phockup>git pull
Already up to date.

P:\Projects\phockup>git checkout feature/maxdepth
Switched to branch 'feature/maxdepth'
Your branch is up to date with 'origin/feature/maxdepth'.

P:\Projects\phockup>git merge master
Already up to date.

P:\Projects\phockup>
```

Looking at the diffs, I can't tell what's different between my feature branch and your master.  I'll maybe try updating from `upstream` again and see if I can get it to sync up.  I was current with the quiet mode PR on my fork, but I must have borked something.  I hope it isn't that weird filename causing issues pulling/pushing to Windows.

**Comment by ivandokov** [comment]
Appologies for the misleading steps. Here is a proper guide how to sync your repo with the upstream https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by unapproachable** [comment]
Okay... so, I moved over to Linux for the upstream work to get the changes pulled (same steps as on Windows), but here they work.  I'm pretty sure the weird filename was preventing something from actually going through, but it was failing silently.  Every time I tried to fetch upstream and merge to master or my branch I had the same error with the file and regardless of how I dealt with it, it came back if I re-ran the fetch.  

Anyway, we look clean now for merging.  I'm just working through the issues list to get practice in Python and since I use phockup.  Hopefully some value added here.

**Comment by ivandokov** [comment]
Looking good now. Can you please add information about the new flag in the readme.

**Pull request merged**
